### ISSUE TITLE
Log ajustarCalibracionBilog.pl

### ISSUE THREAD

**Issue by JoraJora** [SUB-ESTADISTICA-ICFES/SABER-11#3]
![image](https://user-images.githubusercontent.com/9062738/28932058-d3c9d9a8-783d-11e7-8af3-365442038064.png)

@walgarcia , podríamos incluir en el log las constates calculadas para cada ítem, usadas en el ajuste de las calibraciones con una corrida EMPRICIAL ? .

**Comment by walgarcia** [comment]
Se refiere al M y S calculados?

**Comment by walgarcia** [comment]
Listo
